# Generated by Django 2.1.3 on 2021-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('status', models.IntegerField()),
                ('goods', models.CharField(max_length=256)),
                ('packingPrice', models.FloatField()),
                ('deliveryPrice', models.FloatField()),
                ('discount', models.FloatField()),
                ('address', models.IntegerField()),
                ('deliveryMan', models.IntegerField()),
                ('paymentChannels', models.IntegerField()),
                ('addTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
