# Generated by Django 2.1.3 on 2021-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=18)),
                ('registerTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
