# Generated by Django 2.1.3 on 2021-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=32)),
                ('alcohol', models.CharField(max_length=8)),
                ('capacity', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=32)),
                ('shelfLife', models.CharField(max_length=10)),
                ('pic', models.CharField(max_length=256)),
                ('belong', models.IntegerField()),
                ('delete', models.IntegerField()),
                ('addTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
